# Azure Container Apps configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-job-finder
  labels:
    app: ai-job-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-job-finder
  template:
    metadata:
      labels:
        app: ai-job-finder
    spec:
      containers:
      - name: ai-job-finder
        image: your-registry.azurecr.io/ai-job-finder:latest
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          value: "production"
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: google-api-key
        - name: RAPIDAPI_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rapidapi-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-job-finder-service
spec:
  selector:
    app: ai-job-finder
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer